In [88]:
import numpy as np
from scipy.optimize import differential_evolution
from scipy.special import expit

In [89]:
def rw_transfer_llf(para,cue,outcome,action):
    
    """
    Transfer learning RW model
    
    args:
        para: parameter
        
        cue: happy/angry face, +0.5 denotes happy face, -0.5 denotes angry face
        
        outcome: reward/punishement, 1 denotes reward outcome, 0 denotes punishement outcome
        
        action: appraoch/avoidance, 1 denotes appraoch action, 0 denotes avoid action
    
    
    """
    
    alpha,tau,bias0,bias1,ep = para
    
    
    trial_len = len(action)
    nll = 0
    q_u = .5
    
    for t in range(trial_len):
        
        cue_t = cue[t]
        a_t = action[t]
        r_t = outcome[t]
        
        q_t = q_u if cue_t>0 else 1-q_u
        
        ## decision: e-softmax
        
        p_app = expit(tau * (2*q_t - 1) + bias0 + bias1 * cue_t)
        p_app = (1-ep) * p_app + ep/2
        
        
        # log-likelihood
        if a_t == 1:
            p_choice = p_app
        else:
            p_choice = 1 - p_app
        p_choice = np.clip(p_choice, 1e-8, 1 - 1e-8)
        nll -= np.log(p_choice)
        
        
        ## align outcome to happy face appraoch action
        
        rev_outcome = r_t if a_t == 1 else 1 - r_t
        cue_outcome = rev_outcome if cue_t > 0 else 1 - rev_outcome
        
        ## update
        
        q_u  += alpha * (cue_outcome - q_u)
    
    return nll


def rw_seprate_llf(para,cue,outcome,action):
    """
    Separate cue learning RW model
    
    args:
        para: parameter
        
        cue: happy/angry face, +0.5 denotes happy face, -0.5 denotes angry face
        
        outcome: reward/punishement, 1 denotes reward outcome, 0 denotes punishement outcome
        
        action: appraoch/avoidance, 1 denotes appraoch action, 0 denotes avoid action
    
    
    """
    
    alpha,tau,bias0,bias1,ep = para
    
    
    trial_len = len(action)
    nll = 0
    q_h = .5  ## happy face
    q_a = .5  ## angry face
    
    for t in range(trial_len):
        
        cue_t = cue[t]
        a_t = action[t]
        r_t = outcome[t]
        
        q_t = q_h if cue_t>0 else q_a
        
        ## decision: e-softmax
        
        p_app = expit(tau * (2*q_t - 1) + bias0 + bias1 * cue_t)
        p_app = (1-ep) * p_app + ep/2
        
        # log-likelihood
        if a_t == 1:
            p_choice = p_app
        else:
            p_choice = 1 - p_app
        p_choice = np.clip(p_choice, 1e-8, 1 - 1e-8)
        nll -= np.log(p_choice)
        
        
        ## align outcome to happy face appraoch action
        
        rev_outcome = r_t if a_t == 1 else 1 - r_t
        
        ## update
        
        pe = rev_outcome - q_t
        if cue[t] > 0:
            q_h += alpha*pe
        else:
            q_a += alpha*pe
    
    return nll


def fit_model(data):
    
    """
    Fit transfer learning and separate cue learning model
    
    args:
    
        data: list{'cue','outcome','action'}
    
    return:
        result: list('t_para','s_para','t_nll','s_nll')
    
    """
    cue = data['cue']
    outcome = data['outcome']
    action = data['choice']
    
    bounds = [
    (1e-4, 0.9999),   # alpha
    (1e-4, 20.0),    # tau
    (-8.0, 8.0),     # bias0
    (-8.0, 8.0),     # bias1
    (1e-4, 0.999)    # ep
    ]
    
    ## fit transfer learning model
    
    t_result = differential_evolution(
            rw_transfer_llf,
            bounds=bounds,
            args=(cue, outcome, action),
            maxiter=1000,
            popsize=30,
            polish=True,
            disp=True
            )
    
    ## fit separate cue learning model
    
    s_result = differential_evolution(
            rw_seprate_llf,
            bounds=bounds,
            args=(cue, outcome, action),
            maxiter=1000,
            popsize=30,
            polish=True,
            disp=True
            )
    
    return {'t_para':t_result.x,
           's_para':s_result.x,
           't_nll':t_result.fun,
           's_nll':s_result.fun}

In [107]:
## fit models to excluded and included participants
import pandas as pd
ex_dat = pd.read_csv('excluded_stan_fit.csv')
in_dat = pd.read_csv('included_session1_stan_fit.csv')

In [108]:
## select first two blocks
ex_dat['block1_2'] = ex_dat['block1'] + ex_dat['block2']
in_dat['block1_2'] = in_dat['block1'] + in_dat['block2']

ex_dat = ex_dat.loc[ex_dat['block1_2']>0]
in_dat = in_dat.loc[in_dat['block1_2']>0]

In [110]:
ex_grouped = (
    ex_dat.groupby('sub_id')[['choice', 'cue', 'outcome']]
    .apply(lambda df: {
        'choice': df['choice'].tolist(),
        'cue': df['cue'].tolist(),
        'outcome': df['outcome'].tolist()
    })
    .to_dict()
)
in_grouped = (
    in_dat.groupby('sub_id')[['choice','cue','outcome']]
    .apply(lambda df:{
        'choice':df['choice'].tolist(),
        'cue':df['cue'].tolist(),
        'outcome':df['outcome'].tolist()
    }).to_dict()
)

In [112]:
save_ex_fit = {}
save_in_fit = {}

for i,v in ex_grouped.items():
    save_ex_fit[i] = fit_model(v)
for i,v in in_grouped.items():
    save_in_fit[i] = fit_model(v)

differential_evolution step 1: f(x)= 264.7223485274729
differential_evolution step 2: f(x)= 264.7223485274729
differential_evolution step 3: f(x)= 262.56783052541203
differential_evolution step 4: f(x)= 262.56783052541203
differential_evolution step 5: f(x)= 262.56783052541203
differential_evolution step 6: f(x)= 262.56783052541203
differential_evolution step 7: f(x)= 262.56783052541203
differential_evolution step 8: f(x)= 262.3574867434304
differential_evolution step 9: f(x)= 262.3574867434304
differential_evolution step 10: f(x)= 262.3574867434304
differential_evolution step 11: f(x)= 262.3574867434304
differential_evolution step 12: f(x)= 262.2652510426013
Polishing solution with 'L-BFGS-B'
differential_evolution step 1: f(x)= 266.203046376312
differential_evolution step 2: f(x)= 266.0712535386588
differential_evolution step 3: f(x)= 264.9632518649679
differential_evolution step 4: f(x)= 264.8291910381357
differential_evolution step 5: f(x)= 264.8291910381357
differential_evolution step 6: f(x)= 264.8291910381357
differential_evolution step 7: f(x)= 264.8291910381357
Polishing solution with 'L-BFGS-B'
differential_evolution step 1: f(x)= 250.36919267186457
differential_evolution step 2: f(x)= 250.36919267186457
differential_evolution step 3: f(x)= 250.17726498633562
differential_evolution step 4: f(x)= 250.17726498633562
differential_evolution step 5: f(x)= 249.09538629716332
differential_evolution step 6: f(x)= 249.09538629716332
differential_evolution step 7: f(x)= 248.9322309898258
Polishing solution with 'L-BFGS-B'
differential_evolution step 1: f(x)= 268.76933070496034
differential_evolution step 2: f(x)= 268.47099071363436
differential_evolution step 3: f(x)= 267.30392320103084
differential_evolution step 4: f(x)= 267.05965083265176
differential_evolution step 5: f(x)= 267.05965083265176
differential_evolution step 6: f(x)= 267.05965083265176
differential_evolution step 7: f(x)= 267.05965083265176
differential_evolution step 8: f(x)= 267.05965083265176
Polishing solution with 'L-BFGS-B'
differential_evolution step 1: f(x)= 290.5416679134955
differential_evolution step 2: f(x)= 287.8335065717801
differential_evolution step 3: f(x)= 287.48160178230995
differential_evolution step 4: f(x)= 287.3982658102165
differential_evolution step 5: f(x)= 287.3982658102165
differential_evolution step 6: f(x)= 287.3982658102165
differential_evolution step 7: f(x)= 287.3982658102165
Polishing solution with 'L-BFGS-B'
differential_evolution step 1: f(x)= 291.3844113721305
differential_evolution step 2: f(x)= 288.6106830077852
differential_evolution step 3: f(x)= 288.0031664721327
differential_evolution step 4: f(x)= 287.73864784442225
differential_evolution step 5: f(x)= 287.23548840606986
differential_evolution step 6: f(x)= 286.53131008839364
differential_evolution step 7: f(x)= 286.53131008839364
Polishing solution with 'L-BFGS-B'
differential_evolution step 1: f(x)= 199.60499419361534
differential_evolution step 2: f(x)= 197.89066289623707
differential_evolution step 3: f(x)= 197.89066289623707
differential_evolution step 4: f(x)= 197.57925420269794
differential_evolution step 5: f(x)= 197.57925420269794
differential_evolution step 6: f(x)= 197.55813734171775
differential_evolution step 7: f(x)= 196.43255630435658
differential_evolution step 8: f(x)= 196.43255630435658
Polishing solution with 'L-BFGS-B'
differential_evolution step 1: f(x)= 212.9308372715516
differential_evolution step 2: f(x)= 212.87917612949198
differential_evolution step 3: f(x)= 212.25575847375012
differential_evolution step 4: f(x)= 212.21309750688445
differential_evolution step 5: f(x)= 212.21309750688445
Polishing solution with 'L-BFGS-B'
differential_evolution step 1: f(x)= 127.22942825923919
differential_evolution step 2: f(x)= 112.87454776165946
differential_evolution step 3: f(x)= 103.22643232011941
differential_evolution step 4: f(x)= 103.22643232011941
differential_evolution step 5: f(x)= 103.22643232011941
differential_evolution step 6: f(x)= 103.22643232011941
differential_evolution step 7: f(x)= 103.22643232011941
differential_evolution step 8: f(x)= 103.22643232011941
differential_evolution step 9: f(x)= 103.22643232011941
differential_evolution step 10: f(x)= 102.56724099266773
differential_evolution step 11: f(x)= 101.89252847129193
differential_evolution step 12: f(x)= 101.89252847129193
differential_evolution step 13: f(x)= 101.89252847129193
differential_evolution step 14: f(x)= 101.89252847129193
differential_evolution step 15: f(x)= 101.87817244102152
differential_evolution step 16: f(x)= 101.80865498363374
differential_evolution step 17: f(x)= 101.80865498363374
differential_evolution step 18: f(x)= 101.638342904831
differential_evolution step 19: f(x)= 101.638342904831
differential_evolution step 20: f(x)= 101.61122882519398
differential_evolution step 21: f(x)= 101.34459950308224
differential_evolution step 22: f(x)= 101.22034308906136
differential_evolution step 23: f(x)= 101.22034308906136
differential_evolution step 24: f(x)= 101.18344855474923
Polishing solution with 'L-BFGS-B'
differential_evolution step 1: f(x)= 109.25588730046283
differential_evolution step 2: f(x)= 109.1620572619424
differential_evolution step 3: f(x)= 106.0818299932717
differential_evolution step 4: f(x)= 104.0035489914627
differential_evolution step 5: f(x)= 104.0035489914627
differential_evolution step 6: f(x)= 104.0035489914627
differential_evolution step 7: f(x)= 102.87997046651334
differential_evolution step 8: f(x)= 102.35938061810694
differential_evolution step 9: f(x)= 101.10492836763143
differential_evolution step 10: f(x)= 101.10492836763143
differential_evolution step 11: f(x)= 101.07651332486371
differential_evolution step 12: f(x)= 100.86250163568891
differential_evolution step 13: f(x)= 100.86250163568891
differential_evolution step 14: f(x)= 100.12180250399662
differential_evolution step 15: f(x)= 100.01838793128957
differential_evolution step 16: f(x)= 100.01838793128957
differential_evolution step 17: f(x)= 100.01838793128957
differential_evolution step 18: f(x)= 100.01803025864209
differential_evolution step 19: f(x)= 99.95246117075078
Polishing solution with 'L-BFGS-B'
differential_evolution step 1: f(x)= 293.3526497709756
differential_evolution step 2: f(x)= 293.3526497709756
differential_evolution step 3: f(x)= 293.2538122874499
differential_evolution step 4: f(x)= 293.2538122874499
Polishing solution with 'L-BFGS-B'
differential_evolution step 1: f(x)= 290.8003235778711
differential_evolution step 2: f(x)= 290.2943351236863
differential_evolution step 3: f(x)= 287.815310935803
differential_evolution step 4: f(x)= 287.815310935803
differential_evolution step 5: f(x)= 287.815310935803
Polishing solution with 'L-BFGS-B'
differential_evolution step 1: f(x)= 288.10764969428544
differential_evolution step 2: f(x)= 287.6435116322468
differential_evolution step 3: f(x)= 287.4422996189375
differential_evolution step 4: f(x)= 285.05004535709503
differential_evolution step 5: f(x)= 285.05004535709503
differential_evolution step 6: f(x)= 284.9223132074631
differential_evolution step 7: f(x)= 284.9223132074631
differential_evolution step 8: f(x)= 284.9223132074631
differential_evolution step 9: f(x)= 284.9223132074631
differential_evolution step 10: f(x)= 284.9223132074631
differential_evolution step 11: f(x)= 284.2822680499959
differential_evolution step 12: f(x)= 284.2822680499959
differential_evolution step 13: f(x)= 284.2822680499959
differential_evolution step 14: f(x)= 284.2822680499959
differential_evolution step 15: f(x)= 284.1102431277969
Polishing solution with 'L-BFGS-B'
differential_evolution step 1: f(x)= 287.0216106137723
differential_evolution step 2: f(x)= 282.1312988650544
differential_evolution step 3: f(x)= 282.1312988650544
differential_evolution step 4: f(x)= 282.1312988650544
differential_evolution step 5: f(x)= 282.1312988650544
differential_evolution step 6: f(x)= 281.75346918262693
differential_evolution step 7: f(x)= 281.2551597484651
differential_evolution step 8: f(x)= 280.63008197969447
differential_evolution step 9: f(x)= 280.63008197969447
differential_evolution step 10: f(x)= 280.63008197969447
differential_evolution step 11: f(x)= 280.63008197969447
differential_evolution step 12: f(x)= 280.63008197969447
differential_evolution step 13: f(x)= 280.63008197969447
differential_evolution step 14: f(x)= 280.63008197969447
Polishing solution with 'L-BFGS-B'
differential_evolution step 1: f(x)= 252.96471766777967
differential_evolution step 2: f(x)= 251.6496878491663
differential_evolution step 3: f(x)= 251.6496878491663
differential_evolution step 4: f(x)= 251.6496878491663
differential_evolution step 5: f(x)= 251.07521188910337
differential_evolution step 6: f(x)= 251.07521188910337
differential_evolution step 7: f(x)= 251.07521188910337
Polishing solution with 'L-BFGS-B'
differential_evolution step 1: f(x)= 260.14026579393396
differential_evolution step 2: f(x)= 258.08354249061574
differential_evolution step 3: f(x)= 258.08354249061574
differential_evolution step 4: f(x)= 257.14284800362987
differential_evolution step 5: f(x)= 257.14284800362987
differential_evolution step 6: f(x)= 257.14284800362987
differential_evolution step 7: f(x)= 257.14284800362987
differential_evolution step 8: f(x)= 256.9597239295748
differential_evolution step 9: f(x)= 256.9597239295748
differential_evolution step 10: f(x)= 256.9597239295748
Polishing solution with 'L-BFGS-B'
differential_evolution step 1: f(x)= 290.4525819291019
differential_evolution step 2: f(x)= 290.4183915886275
differential_evolution step 3: f(x)= 287.3330855506199
differential_evolution step 4: f(x)= 287.3330855506199
differential_evolution step 5: f(x)= 287.3330855506199
differential_evolution step 6: f(x)= 287.3330855506199
Polishing solution with 'L-BFGS-B'
differential_evolution step 1: f(x)= 280.8236005581449
differential_evolution step 2: f(x)= 280.8236005581449
differential_evolution step 3: f(x)= 280.8031813899207
differential_evolution step 4: f(x)= 279.9150430111177
differential_evolution step 5: f(x)= 279.9150430111177
differential_evolution step 6: f(x)= 279.9150430111177
differential_evolution step 7: f(x)= 279.9150430111177
Polishing solution with 'L-BFGS-B'
differential_evolution step 1: f(x)= 193.01049414964368
differential_evolution step 2: f(x)= 186.22258054202374
differential_evolution step 3: f(x)= 186.22258054202374
differential_evolution step 4: f(x)= 183.90231267419523
differential_evolution step 5: f(x)= 183.90231267419523
differential_evolution step 6: f(x)= 183.90231267419523
differential_evolution step 7: f(x)= 183.1724300090199
differential_evolution step 8: f(x)= 183.1724300090199
differential_evolution step 9: f(x)= 182.87513951013423
differential_evolution step 10: f(x)= 182.87513951013423
differential_evolution step 11: f(x)= 182.72884363908358
differential_evolution step 12: f(x)= 182.0729703132415
differential_evolution step 13: f(x)= 182.0729703132415
differential_evolution step 14: f(x)= 182.0729703132415
differential_evolution step 15: f(x)= 181.91061127782416
Polishing solution with 'L-BFGS-B'
differential_evolution step 1: f(x)= 231.00288286359688
differential_evolution step 2: f(x)= 225.74062627493845
differential_evolution step 3: f(x)= 224.9684005703758
differential_evolution step 4: f(x)= 224.9684005703758
differential_evolution step 5: f(x)= 224.9684005703758
differential_evolution step 6: f(x)= 224.09771472646892
differential_evolution step 7: f(x)= 224.09771472646892
differential_evolution step 8: f(x)= 222.80227588915858
differential_evolution step 9: f(x)= 222.80227588915858
differential_evolution step 10: f(x)= 222.80227588915858
differential_evolution step 11: f(x)= 222.80227588915858
differential_evolution step 12: f(x)= 222.80227588915858
differential_evolution step 13: f(x)= 222.80153795705806
differential_evolution step 14: f(x)= 222.71211256943138
Polishing solution with 'L-BFGS-B'
differential_evolution step 1: f(x)= 199.78400246431673
differential_evolution step 2: f(x)= 194.4069210849
differential_evolution step 3: f(x)= 194.4069210849
differential_evolution step 4: f(x)= 188.86282671638313
differential_evolution step 5: f(x)= 188.86282671638313
differential_evolution step 6: f(x)= 188.5512710114108
differential_evolution step 7: f(x)= 187.44251060786726
differential_evolution step 8: f(x)= 183.20596868682273
differential_evolution step 9: f(x)= 183.20596868682273
differential_evolution step 10: f(x)= 182.6638093420281
differential_evolution step 11: f(x)= 182.6638093420281
differential_evolution step 12: f(x)= 182.6638093420281
differential_evolution step 13: f(x)= 182.57907312171795
differential_evolution step 14: f(x)= 181.8803251837666
differential_evolution step 15: f(x)= 181.8803251837666
differential_evolution step 16: f(x)= 181.8803251837666
differential_evolution step 17: f(x)= 181.62505642832355
differential_evolution step 18: f(x)= 181.62505642832355
differential_evolution step 19: f(x)= 181.6222617726845
differential_evolution step 20: f(x)= 181.51959352819554
differential_evolution step 21: f(x)= 181.51959352819554
differential_evolution step 22: f(x)= 181.51959352819554
Polishing solution with 'L-BFGS-B'
differential_evolution step 1: f(x)= 227.86890065412982
differential_evolution step 2: f(x)= 227.86890065412982
differential_evolution step 3: f(x)= 227.86890065412982
differential_evolution step 4: f(x)= 226.86939314168472
differential_evolution step 5: f(x)= 226.86939314168472
differential_evolution step 6: f(x)= 226.86939314168472
differential_evolution step 7: f(x)= 225.46810633966382
differential_evolution step 8: f(x)= 225.46810633966382
differential_evolution step 9: f(x)= 223.4085519093556
differential_evolution step 10: f(x)= 223.4085519093556
differential_evolution step 11: f(x)= 223.4085519093556
differential_evolution step 12: f(x)= 223.4085519093556
differential_evolution step 13: f(x)= 223.4085519093556
differential_evolution step 14: f(x)= 223.4085519093556
differential_evolution step 15: f(x)= 223.4085519093556
differential_evolution step 16: f(x)= 223.4085519093556
differential_evolution step 17: f(x)= 223.4085519093556
differential_evolution step 18: f(x)= 223.4085519093556
differential_evolution step 19: f(x)= 223.4085519093556
differential_evolution step 20: f(x)= 223.4085519093556
differential_evolution step 21: f(x)= 223.4085519093556
Polishing solution with 'L-BFGS-B'
differential_evolution step 1: f(x)= 223.92097504638943
differential_evolution step 2: f(x)= 221.0821529067943
differential_evolution step 3: f(x)= 221.0821529067943
differential_evolution step 4: f(x)= 221.0821529067943
differential_evolution step 5: f(x)= 220.1442385535061
differential_evolution step 6: f(x)= 220.1442385535061
differential_evolution step 7: f(x)= 220.1442385535061
differential_evolution step 8: f(x)= 219.62931252576485
differential_evolution step 9: f(x)= 217.3484399298506
differential_evolution step 10: f(x)= 217.3484399298506
differential_evolution step 11: f(x)= 217.3373594536472
differential_evolution step 12: f(x)= 217.3373594536472
differential_evolution step 13: f(x)= 216.70939845855202
differential_evolution step 14: f(x)= 216.70939845855202
differential_evolution step 15: f(x)= 216.70939845855202
differential_evolution step 16: f(x)= 216.69512206131648
differential_evolution step 17: f(x)= 216.69512206131648
differential_evolution step 18: f(x)= 216.69512206131648
differential_evolution step 19: f(x)= 216.6454062987747
differential_evolution step 20: f(x)= 216.49051752015572
differential_evolution step 21: f(x)= 216.45373720385126
Polishing solution with 'L-BFGS-B'
differential_evolution step 1: f(x)= 224.63504136356633
differential_evolution step 2: f(x)= 224.63504136356633
differential_evolution step 3: f(x)= 220.9890495183369
differential_evolution step 4: f(x)= 220.9890495183369
differential_evolution step 5: f(x)= 220.9890495183369
differential_evolution step 6: f(x)= 220.9890495183369
differential_evolution step 7: f(x)= 220.00158330961253
differential_evolution step 8: f(x)= 220.00158330961253
differential_evolution step 9: f(x)= 220.00158330961253
differential_evolution step 10: f(x)= 220.00158330961253
differential_evolution step 11: f(x)= 219.96487945239147
differential_evolution step 12: f(x)= 219.96487945239147
differential_evolution step 13: f(x)= 219.61778259268112
differential_evolution step 14: f(x)= 219.61778259268112
Polishing solution with 'L-BFGS-B'
differential_evolution step 1: f(x)= 237.8765703075572
differential_evolution step 2: f(x)= 231.66380883677542
differential_evolution step 3: f(x)= 231.66380883677542
differential_evolution step 4: f(x)= 231.66380883677542
differential_evolution step 5: f(x)= 231.66380883677542
differential_evolution step 6: f(x)= 229.48507051744608
differential_evolution step 7: f(x)= 229.48507051744608
differential_evolution step 8: f(x)= 229.48507051744608
differential_evolution step 9: f(x)= 229.37019886628204
differential_evolution step 10: f(x)= 229.37019886628204
differential_evolution step 11: f(x)= 229.37019886628204
differential_evolution step 12: f(x)= 229.21227763067952
differential_evolution step 13: f(x)= 229.21227763067952
Polishing solution with 'L-BFGS-B'
differential_evolution step 1: f(x)= 222.5122558103849
differential_evolution step 2: f(x)= 219.59889686096267
differential_evolution step 3: f(x)= 218.35735093440286
differential_evolution step 4: f(x)= 217.95445034184277
differential_evolution step 5: f(x)= 217.95445034184277
differential_evolution step 6: f(x)= 216.5872479513601
differential_evolution step 7: f(x)= 216.5872479513601
differential_evolution step 8: f(x)= 216.5872479513601
differential_evolution step 9: f(x)= 216.5872479513601
differential_evolution step 10: f(x)= 216.5872479513601
differential_evolution step 11: f(x)= 216.15531875524718
differential_evolution step 12: f(x)= 215.45219018614094
differential_evolution step 13: f(x)= 215.03051839467696
differential_evolution step 14: f(x)= 215.03051839467696
differential_evolution step 15: f(x)= 214.8052839265676
differential_evolution step 16: f(x)= 214.6353773127382
differential_evolution step 17: f(x)= 214.6353773127382
differential_evolution step 18: f(x)= 214.57958699872216
Polishing solution with 'L-BFGS-B'
differential_evolution step 1: f(x)= 235.39616445787235
differential_evolution step 2: f(x)= 232.9647054093313
differential_evolution step 3: f(x)= 232.9647054093313
differential_evolution step 4: f(x)= 232.9647054093313
differential_evolution step 5: f(x)= 231.16251154876707
differential_evolution step 6: f(x)= 231.16251154876707
differential_evolution step 7: f(x)= 230.68876260143563
differential_evolution step 8: f(x)= 230.68876260143563
differential_evolution step 9: f(x)= 230.68876260143563
differential_evolution step 10: f(x)= 229.62705590672266
differential_evolution step 11: f(x)= 229.31423263550278
differential_evolution step 12: f(x)= 229.31423263550278
differential_evolution step 13: f(x)= 227.82098613849942
differential_evolution step 14: f(x)= 227.65551499360362
differential_evolution step 15: f(x)= 227.12553339101348
differential_evolution step 16: f(x)= 226.88987322263756
Polishing solution with 'L-BFGS-B'
differential_evolution step 1: f(x)= 239.79332124754615
differential_evolution step 2: f(x)= 239.79332124754615
differential_evolution step 3: f(x)= 239.79332124754615
differential_evolution step 4: f(x)= 239.168161610792
differential_evolution step 5: f(x)= 239.168161610792
differential_evolution step 6: f(x)= 237.7772432415475
differential_evolution step 7: f(x)= 236.40085094648254
differential_evolution step 8: f(x)= 236.40085094648254
differential_evolution step 9: f(x)= 235.4400222409714
differential_evolution step 10: f(x)= 235.4400222409714
differential_evolution step 11: f(x)= 235.4400222409714
differential_evolution step 12: f(x)= 235.4400222409714
differential_evolution step 13: f(x)= 235.05347973045764
differential_evolution step 14: f(x)= 235.05347973045764

In [115]:
t_nll = pd.DataFrame(save_in_fit).loc['t_nll',:]
s_nll = pd.DataFrame(save_in_fit).loc['s_nll',:]
s_ep = []
t_ep = []
for i in range(13):
    s_ep.append(1-pd.DataFrame(save_in_fit).loc['s_para',i+1][-1])
    t_ep.append(1-pd.DataFrame(save_in_fit).loc['t_para',i+1][-1])
pd.DataFrame({'transfer learning':t_nll,
             "separate cue learning":s_nll,
                          'transfer learning ep':t_ep,
             'separate learning ep':s_ep})

,transfer learning,separate cue learning,transfer learning ep,separate learning ep
1,181.685312,222.631344,0.836460,0.686299
2,181.386898,222.888162,0.998149,0.753343
3,216.265353,219.003797,0.797266,0.728815
4,228.715677,213.830017,0.691576,0.737925
5,226.69576,234.909335,0.918128,0.790783
6,128.950824,240.627034,0.879811,0.596786
7,216.908253,233.079924,0.999900,0.999900
8,238.683349,260.12524,0.715545,0.760753
9,171.757818,207.327364,0.952706,0.979478
10,208.119168,127.149154,0.999900,0.880981
11,259.317678,280.434403,0.502139,0.387119
12,159.398138,183.40892,0.999900,0.999900
13,219.646153,232.877482,0.999900,0.999900

In [116]:
t_nll = pd.DataFrame(save_ex_fit).loc['t_nll',:]
s_nll = pd.DataFrame(save_ex_fit).loc['s_nll',:]
s_ep = []
t_ep = []
for i in range(9):
    s_ep.append(1-pd.DataFrame(save_ex_fit).loc['s_para',i+1][-1])
    t_ep.append(1-pd.DataFrame(save_ex_fit).loc['t_para',i+1][-1])
pd.DataFrame({'transfer learning':t_nll,
             "separate cue learning":s_nll,
             'transfer learning ep':t_ep,
             'separate learning ep':s_ep})

,transfer learning,separate cue learning,transfer learning ep,separate learning ep
1,261.643649,264.5887,0.608958,0.407933
2,246.901791,266.712606,0.634343,0.426292
3,287.069156,285.708582,0.306598,0.303452
4,196.185877,211.991883,0.449677,0.216066
5,101.104334,99.897701,0.923080,0.927817
6,292.723835,287.188266,0.200066,0.235506
7,283.68883,279.937377,0.999900,0.999900
8,250.890489,256.283398,0.448191,0.999900
9,286.608565,278.960993,0.277061,0.345838